DecisionLens AI

This notebook prepares the raw datasets for model training by applying a minimal preprocessing pipeline.

The following steps are performed:

- Load the raw datasets.
- Select the required columns.
- Apply text preprocessing.
- Save the processed datasets.

Import Libraries

In [40]:
import pandas as pd
import numpy as np

Load Train, Test, Validation Data

In [41]:
train_df = pd.read_csv('/content/drive/MyDrive/PROYECT_5/train.csv')
test_df = pd.read_csv('/content/drive/MyDrive/PROYECT_5/test.csv')
validation_df = pd.read_csv('/content/drive/MyDrive/PROYECT_5/validation.csv')

In [42]:
print(train_df.shape)
print(test_df.shape)
print(validation_df.shape)

(20974, 9)
(6315, 9)
(3208, 9)

In [43]:
train_df.head()

,argument,topic,set,WA,MACE-P,stance_WA,stance_WA_conf,character_count,word_count
0,"""marriage"" isn't keeping up with the times. a...",We should abandon marriage,train,0.846165,0.297659,1,1.000000,157,27
1,.a multi-party system would be too confusing a...,We should adopt a multi-party system,train,0.891271,0.726133,-1,1.000000,112,18
2,`people reach their limit when it comes to the...,Assisted suicide should be a criminal offence,train,0.730395,0.225212,-1,1.000000,208,40
3,"100% agree, should they do that, it would be a...",We should abolish safe spaces,train,0.236686,0.004104,1,0.805517,57,12
4,A ban on naturopathy creates a cohesive front ...,We should ban naturopathy,train,0.753805,0.337724,1,1.000000,153,22

Select just Required Features

In [44]:
train_processed = train_df[['argument', 'stance_WA']].copy()
test_processed = test_df[['argument', 'stance_WA']].copy()
validation_processed = validation_df[['argument', 'stance_WA']].copy()

In [45]:
train_processed.head()

                                            argument  stance_WA
0  "marriage" isn't keeping up with the times.  a...          1
1  .a multi-party system would be too confusing a...         -1
2  `people reach their limit when it comes to the...         -1
3  100% agree, should they do that, it would be a...          1
4  A ban on naturopathy creates a cohesive front ...          1

In [46]:
test_processed.head()

                                            argument  stance_WA
0  6 million people died so to deny the holocaust...          1
1  a ban would only bring problems in gender equa...         -1
2  A centralized system of criminal defense would...          1
3  a constantly growing population requires large...         -1
4  a country would fall apart under libertarianis...         -1

In [47]:
validation_processed.head()

                                            argument  stance_WA
0  \ero-tolerance policy in schools should not be...         -1
1  a bad score in an intelligence test is a blow ...          1
2  a bad score in an intelligence test is a blow ...          1
3  A ban would send a strong message that better ...          1
4  a blockade is sometimes the only non-violent o...         -1

Convert Text to Lowercase

In [48]:
train_processed['argument'] = train_processed['argument'].str.lower()
test_processed['argument'] = test_processed['argument'].str.lower()
validation_processed['argument'] = validation_processed['argument'].str.lower()

In [49]:
train_processed.head()

                                            argument  stance_WA
0  "marriage" isn't keeping up with the times.  a...          1
1  .a multi-party system would be too confusing a...         -1
2  `people reach their limit when it comes to the...         -1
3  100% agree, should they do that, it would be a...          1
4  a ban on naturopathy creates a cohesive front ...          1

Normalize Whitespace

In [50]:
train_processed['argument'] = train_processed['argument'].str.strip()
train_processed['argument'] = train_processed['argument'].str.replace(r'\s+', ' ', regex=True)

In [51]:
test_processed['argument'] = test_processed['argument'].str.strip()
test_processed['argument'] = test_processed['argument'].str.replace(r'\s+', ' ', regex=True)

In [52]:
validation_processed['argument'] = validation_processed['argument'].str.strip()
validation_processed['argument'] = validation_processed['argument'].str.replace(r'\s+', ' ', regex=True)

In [53]:
train_processed.sample(n=5, random_state=42)

                                                argument  stance_WA
2516   collectivism does not reward individuals for h...          1
19687  we shouldn't ban cosmetic surgery altogether b...         -1
12354  safe spaces provide a needed service, to give ...         -1
19139  we should not prohibit flag burning because if...         -1
9298   marriage is an outdated, patriarchal and histo...          1

Save Processed Data

In [55]:
train_processed.to_csv('/content/drive/MyDrive/PROYECT_5/train_processed.csv', index=False)
test_processed.to_csv('/content/drive/MyDrive/PROYECT_5/test_processed.csv', index=False)
validation_processed.to_csv('/content/drive/MyDrive/PROYECT_5/validation_processed.csv', index=False)

Summary

- Loaded the raw training, validation and test datasets.
- Selected only the columns required for model training.
- Converted all text to lowercase.
- Normalized whitespace by removing extra spaces.
- Saved the processed datasets for the modelling stage.